# Generated by Django 5.1.4 on 2025-02-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Science",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="название науки")),
            ],
        ),
        migrations.CreateModel(
            name="GroupScience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod",
                    models.CharField(max_length=9, unique=True, verbose_name="код"),
                ),
                (
                    "title",
                    models.CharField(unique=True, verbose_name="название группы"),
                ),
                (
                    "science",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="fgos.science",
                        verbose_name="наука",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="код специальности"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        unique=True, verbose_name="название специальности"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialitys",
                        to="fgos.groupscience",
                        verbose_name="группа специальностей",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FGOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="название ФГОС"),
                ),
                ("file", models.FileField(upload_to="fgos/", verbose_name="файл ФГОС")),
                ("date", models.DateField(verbose_name="дата приказа")),
                (
                    "number",
                    models.CharField(max_length=6, verbose_name="номер приказа"),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fgos.speciality",
                        verbose_name="специальность",
                    ),
                ),
            ],
        ),
    ]
