# Generated by Django 5.1.4 on 2025-02-20 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="название курса"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="краткое описание, цель"),
                ),
                ("icon", models.ImageField(upload_to="", verbose_name="иконка")),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="тема урока")),
                ("content", models.TextField(verbose_name="содержимое урока")),
                (
                    "cource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="service.course",
                        verbose_name="курс",
                    ),
                ),
            ],
        ),
    ]
