# Generated by Django 5.1.4 on 2025-02-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_remove_lesson_cource_lesson_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competetion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="код компетенции"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=160, verbose_name="описание"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="рабочая программа"
            ),
        ),
    ]
