# Generated by Django 5.1.4 on 2025-02-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_competetion_course_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="competetion",
            name="transcript",
            field=models.CharField(
                blank=True, max_length=28, null=True, verbose_name="расшифровка кода"
            ),
        ),
    ]
