# Generated by Django 5.1.4 on 2025-02-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_competetiontype_remove_competetion_transcript_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competetion",
            name="description",
            field=models.CharField(max_length=190, verbose_name="описание"),
        ),
    ]
