# Generated by Django 5.1.4 on 2025-02-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_alter_competetion_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiviteType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="вид деятельности")),
            ],
        ),
        migrations.AlterField(
            model_name="competetion",
            name="typecompetetion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="service.competetiontype",
                verbose_name="вид компетенции",
            ),
        ),
        migrations.AddField(
            model_name="competetion",
            name="activite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="service.activitetype",
                verbose_name="вид деятельности",
            ),
        ),
    ]
