# Generated by Django 5.1.4 on 2025-02-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_activitetype_alter_competetion_typecompetetion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitetype",
            name="name",
            field=models.CharField(max_length=120, verbose_name="вид деятельности"),
        ),
        migrations.AlterField(
            model_name="competetion",
            name="typecompetetion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="service.competetiontype",
                verbose_name="вид компетенции",
            ),
        ),
    ]
