# Generated by Django 5.1.4 on 2025-02-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_activitetype_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skilltype",
                    models.CharField(
                        choices=[
                            ("knowledge", "знание"),
                            ("ability", "умение"),
                            ("experience", "навык"),
                        ],
                        default="knowledge",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(verbose_name="требование к скилу")),
            ],
            options={
                "verbose_name": "скилл",
                "verbose_name_plural": "скилы",
            },
        ),
        migrations.AlterModelOptions(
            name="activitetype",
            options={
                "verbose_name": "вид деятельности",
                "verbose_name_plural": "виды деятельности",
            },
        ),
        migrations.AlterModelOptions(
            name="competetion",
            options={
                "verbose_name": "компетенция",
                "verbose_name_plural": "компетенции",
            },
        ),
        migrations.AlterModelOptions(
            name="competetiontype",
            options={
                "verbose_name": "тип компетенции",
                "verbose_name_plural": "типы компетенций",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "курс", "verbose_name_plural": "курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "урок", "verbose_name_plural": "уроки"},
        ),
    ]
