# Generated by Django 5.1.4 on 2025-02-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_skill_alter_activitetype_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("skilltype", "title")},
        ),
    ]
