# Generated by Django 5.1.4 on 2025-02-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_activitetype_skills_alter_skill_skilltype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.AddField(
            model_name="course",
            name="skills",
            field=models.ManyToManyField(
                to="service.skill", verbose_name="требуемые результаты"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="краткое содержимое"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="hour",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="к-во часов"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="num",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="номер урока"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="typelesson",
            field=models.CharField(
                choices=[
                    ("remember", "вспомнить материал"),
                    ("newskill", "узнать новое"),
                    ("practice", "практика"),
                    ("selfwork", "самостоятельная работа"),
                ],
                default="newskill",
                max_length=10,
                verbose_name="тип урока",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="краткое описание, цель"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="содержимое урока"
            ),
        ),
        migrations.CreateModel(
            name="ChapterLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="номер главы"),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="название раздела"),
                ),
                ("description", models.TextField(verbose_name="описание раздела")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapters",
                        to="service.course",
                        verbose_name="курс",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="service.chapterlesson",
                verbose_name="раздел курса",
            ),
        ),
    ]
