# Generated by Django 5.1.4 on 2024-12-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="url",
            field=models.CharField(max_length=50, verbose_name="Ссылка"),
        ),
    ]
