# Generated by Django 5.1.4 on 2024-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_menu_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsefulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("url", models.URLField()),
                ("description", models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
