# Generated by Django 5.1.4 on 2025-02-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfessionalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="сфера деятельности"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="тип профессии"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfStandart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regnum",
                    models.PositiveIntegerField(verbose_name="регистрационный номер"),
                ),
                (
                    "cod",
                    models.CharField(unique=True, verbose_name="код профстандарта"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="название профессии"
                    ),
                ),
                (
                    "numorder",
                    models.CharField(max_length=25, verbose_name="номер приказа"),
                ),
                ("dateorder", models.DateField(verbose_name="дата приказа")),
                (
                    "profarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profstandarts",
                        to="profstandart.professionalarea",
                        verbose_name="сфера деятельности",
                    ),
                ),
                (
                    "proftype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profstandarts",
                        to="profstandart.professionaltype",
                        verbose_name="тип профессии",
                    ),
                ),
            ],
        ),
    ]
