# Generated by Django 5.1.4 on 2025-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profstandart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalarea",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="сфера деятельности"
            ),
        ),
        migrations.AlterField(
            model_name="professionaltype",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="тип профессии"
            ),
        ),
    ]
