# Generated by Django 5.1.4 on 2025-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profstandart", "0003_alter_professionalarea_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalarea",
            name="name",
            field=models.CharField(
                max_length=164, unique=True, verbose_name="сфера деятельности"
            ),
        ),
    ]
