# Generated by Django 5.1.4 on 2024-12-07 17:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="основной текст"
            ),
        ),
    ]
