# Generated by Django 5.1.4 on 2025-01-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_categorytree"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryTree",
        ),
    ]
