# Generated by Django 5.1.4 on 2025-01-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_categorytree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.AlterModelOptions(
            name="categorytree",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
