# Generated by Django 5.1.4 on 2025-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytree",
            name="description",
            field=models.TextField(
                blank=True, max_length=60, null=True, verbose_name="описание"
            ),
        ),
        migrations.AddField(
            model_name="categorytree",
            name="order",
            field=models.IntegerField(
                default=1, help_text="значимость категории", verbose_name="сортировка"
            ),
        ),
    ]
