# Generated by Django 5.1.4 on 2025-02-12 03:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_categorytree_description_categorytree_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorytree",
            options={
                "ordering": ("order",),
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AddConstraint(
            model_name="categorytree",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                name="category_title_case_insensitive_unique",
                violation_error_message="Категория уже существует",
            ),
        ),
    ]
